{% set name = "python-utils" %}
{% set version = "2.2.0" %}
{% set sha256 = 'd9b8ab1f2a7c8f26ed16a47505f589a5d51c0d1e55869ab40c20e1c4b42af2c0' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - six

test:
  imports:
    - python_utils
    - python_utils.converters
    - python_utils.formatters

about:
  home: https://github.com/WoLpH/python-utils
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Python Utils is a collection of small Python functions and classes which make common patterns shorter and easier.'
  description: |
    Python Utils is a collection of small Python functions and classes which make common patterns shorter and easier. It is by no means a complete collection but it has served me quite a bit in the past and I will keep extending it.
    One of the libraries using Python Utils is Django Utils.
  doc_url: http://python-utils.readthedocs.io/
  dev_url: https://github.com/WoLpH/python-utils

extra:
  recipe-maintainers:
    - maartenbreddels
    - WoLpH
    - stuertz
