# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eKF69hLB800Kb0Kx8lqPB4rP+W+rRJBs8awV1u2D7HpvMdrYCzXXdcr/vSF4Xp2ZqvRVtaBlhIdY4Ja42hrVEwBnIUMfu6XfqQskiyc6yJ4IIR0Ajb+pHBtVmUqJLA6pnfOEeIhz/CHlAgkeB7urYzhaCQMhChqnK0Dpe4JQ20rDJzlXLC/ip0JTcUQscC749MMOVv6QaY6ShxPNV9T1fCGTfmqlJKx0Jibj4/q1+Iq7HXKB+qK3MekTNpe+fqVmMB64OQvyyjzgQbsnZisvXZSD3iAWZDTdoz+xP02u2WRiZz5mZltieXL4SXgUe2rQThMeCANIYCbgTeM9nQ1ZCNx1IiUgQT3Dn8XoDfQCo1aNsjPXakhfWUc7kP5OI0RMrfh1Opjrkrc4DvansqLC++9ksh0ibE+ix4dlryadGpU8I0AZWYno6fE2a+3YwdIfd00SohHYKYFep8Bk/YUY21ydcQSZn021kjKp7U4PtcEqriPMFOFC5IjK9nDgWHEnQuDatNZxdNbu1S4Vge0VawAl1gGjGHzZyPmqAs+hEbb4AadpMsaxlvPOtP/qFYKQRg1V8OGBsyaLfCKS+uWNNBxCf4+esmy8Slfrf3AWsXrFUeiwVB/XWgHJhtcPlm3u+xn9AZSvuLDvDChZy2q1elVjhkUUmi/bQXV77rdqtiE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
