travis:
  secure:
    BINSTAR_TOKEN: eKF69hLB800Kb0Kx8lqPB4rP+W+rRJBs8awV1u2D7HpvMdrYCzXXdcr/vSF4Xp2ZqvRVtaBlhIdY4Ja42hrVEwBnIUMfu6XfqQskiyc6yJ4IIR0Ajb+pHBtVmUqJLA6pnfOEeIhz/CHlAgkeB7urYzhaCQMhChqnK0Dpe4JQ20rDJzlXLC/ip0JTcUQscC749MMOVv6QaY6ShxPNV9T1fCGTfmqlJKx0Jibj4/q1+Iq7HXKB+qK3MekTNpe+fqVmMB64OQvyyjzgQbsnZisvXZSD3iAWZDTdoz+xP02u2WRiZz5mZltieXL4SXgUe2rQThMeCANIYCbgTeM9nQ1ZCNx1IiUgQT3Dn8XoDfQCo1aNsjPXakhfWUc7kP5OI0RMrfh1Opjrkrc4DvansqLC++9ksh0ibE+ix4dlryadGpU8I0AZWYno6fE2a+3YwdIfd00SohHYKYFep8Bk/YUY21ydcQSZn021kjKp7U4PtcEqriPMFOFC5IjK9nDgWHEnQuDatNZxdNbu1S4Vge0VawAl1gGjGHzZyPmqAs+hEbb4AadpMsaxlvPOtP/qFYKQRg1V8OGBsyaLfCKS+uWNNBxCf4+esmy8Slfrf3AWsXrFUeiwVB/XWgHJhtcPlm3u+xn9AZSvuLDvDChZy2q1elVjhkUUmi/bQXV77rdqtiE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
